### ISSUE TITLE
VGG16 fails in Pytorch

### ISSUE THREAD

**Issue by kkontny** [AmpereComputingAI/ampere_model_library#124]
Inside `ghcr.io/amperecomputingai/arm_aml_pytorch:fa0620f` container:

After launching run.py script i got following error:

```
/onspecta/model_zoo_dev/ampere_model_library/computer_vision/classification/vgg_16# AIO_NUM_THREADS=16 IMAGENET_IMG_PATH=/onspecta/model_zoo_dev/downloads/ImageNet/ILSVRC2012_onspecta/ IMAGENET_LABELS_PATH=/onspecta/model_zoo_dev/downloads/ImageNet/imagenet_labels_onspecta.txt python run.py -p fp32 -f pytorch
Segmentation fault (core dumped)
```

The problem is importing TF in this file, when I comment out following lines from the script:
#from utils.tf import TFFrozenModelRunner
#from utils.tflite import TFLiteRunner
The script works. All models that supports directly both Pytorch and TF has this issue.

**Comment by MarcelWilnicki** [comment]
I am working on rearranging imports to solve this issue
