### ISSUE TITLE
Missing TBTracer

### ISSUE THREAD

**Issue by jerrybdev** [AmpereComputingAI/ampere_model_library#145]
file: model_zoo/utils/profiler_wrapper.py
Model zoo commit: 7d174673bde0ffd078bf053f8dd49703060591af

**Comment by jan-grzybek-ampere** [comment]
Tensorboard profiler is already present in AML main. It can be enabled at runtime with PROFILER=1 env.
See: https://github.com/AmpereComputingAI/ampere_model_library/blob/main/utils/tf.py (16:27)
