### ISSUE TITLE
Pytorch Roberta Base Squad fails accuracy tests

### ISSUE THREAD

**Issue by kkontny** [AmpereComputingAI/ampere_model_library#157]
Please see https://github.com/AmpereComputingAI/DlsLib/issues/1321
I've run it with AIO_PROCESS_MODE=0, without AIO support, it fails with same result.

**Comment by jan-grzybek-ampere** [comment]
@dkupnicki is this fixed now?

**Comment by dkupnicki** [comment]
Yes, closing this issue
